<?php

/**
 * @file
 * Contains wechat.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wechat_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wechat module.
    case 'help.page.wechat':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal wechat module') . '</p>';
      return $output;

    default:
  }
}
